app = "digital-diary-app"
primary_region = "syd"

[build]

[env]
  RAILS_ENV = "production"
  RAILS_SERVE_STATIC_FILES = "true"
  RAILS_LOG_TO_STDOUT = "true"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[mounts]
  source = "diary_storage"
  destination = "/rails/storage"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
