# Nixpacks configuration for Rails app
[phases.setup]
nixPkgs = ["nodejs", "yarn", "postgresql"]

[phases.install]
dependsOn = ["setup"]

[phases.build]
dependsOn = ["install"]
cmds = [
  "bundle install --deployment --without development test",
  "bundle exec rails assets:precompile",
  "chmod +x bin/railway-start"
]

[start]
cmd = "bin/railway-start"

[variables]
RAILS_ENV = "production"
RAILS_SERVE_STATIC_FILES = "true"
RAILS_LOG_TO_STDOUT = "true"
NODE_ENV = "production"
